export {default as LoginScreen} from "./login"
export {default as CadastrarScreen} from "./cadastrar"
export {default as PerfilScreen} from "./perfil"
export { default as PostsTScreen } from "./postsT"
export { default as MapScreen } from "./Map"
export { default as SairScreen } from "./Sair"
export { default as QrCodeScreen } from "./QrCode"
export { default as CameraScreen } from "./Camera"
export { default as ArquivoScreen } from "./Arquivo"
export { default as EnviarMensagemScreen } from "./EnviarMensagem"